#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

PLGPATH="/boot/config/plugins/nut-dw"
CONFIG="$PLGPATH/nut-dw.cfg"
NOTIFY="/usr/local/emhttp/plugins/dynamix/scripts/notify"
HOST="$(echo "$HOSTNAME" | awk '{print toupper($0)}')"
EVENT="UPS Status"

# shellcheck disable=SC2329
handle_term() {
    echo "has received a termination signal" | logger -t "nut-notify[$$]"
    exit 0
}

# shellcheck disable=SC2329
handle_end() {
    echo "is now exiting from handling ${NOTIFYTYPE:-UNKNOWN}" | logger -t "nut-notify[$$]"
}

trap handle_term SIGTERM SIGINT
trap handle_end EXIT

echo "is now handling ${NOTIFYTYPE:-UNKNOWN}" | logger -t "nut-notify[$$]"

# read our configuration
[ -e "$CONFIG" ] && source "$CONFIG"

# shellcheck disable=SC1091
[ -e "/etc/nut/xnut-notify-hooks.sh" ] && source "/etc/nut/xnut-notify-hooks.sh"

SUBJECT="[${HOST}] NUT: [${NAME}@${IPADDR}] UPS"

if [ "$SHUTDOWN" == "batt_level" ]; then
    TIMER="$BATTERYLEVEL"
    MESSAGE="The system will shutdown when the UPS battery charge reaches ${BATTERYLEVEL}%."
    BATTERY="battery.charge"
fi

if [ "$SHUTDOWN" == "batt_timer" ]; then
    TIMER="$RTVALUE"
    MESSAGE="The system will shutdown when there is ${RTVALUE} ${RTUNIT} runtime left on the UPS battery."
    BATTERY="$RUNTIME"
fi

if [ "$SHUTDOWN" == "sec_timer" ]; then
    TIMER="$TIMEOUT"
    MESSAGE="The system will shutdown in ${TIMEOUT} seconds."
    BATTERY=""
fi

if [ "$NOTIFYTYPE" == "ONLINE" ]
then
        echo "Terminating monitoring instances of the program..." | logger -t "nut-notify[$$]"
        pgrep -f "/usr/sbin/nut-notify" | grep -v "^$$\$" | xargs -rt kill -s SIGTERM 2>&1 | logger -t "nut-notify[$$]"

        echo "[${NAME}] UPS is online, any planned shutdowns were cancelled." | tee >(wall) >(logger -t "nut-notify[$$]")

        if [ "$(type -t "ONLINE")" == "function" ]; then
            echo "Executing user's hook script for ONLINE (as non-blocking)..." | logger -t "nut-notify[$$]"
            ( ONLINE 2>&1 | logger -t "xnut-notify-hooks.sh[$$]" ) &
        fi

        echo "Sending OS notifications..." | logger -t "nut-notify[$$]"
        timeout -s9 15 "$NOTIFY" -e "${EVENT}" -s "Notice ${SUBJECT} On Line" -d "UPS is online, any planned shutdowns were cancelled." -i "normal"
        if [ $? -gt 100 ]; then
            echo "OS notifications could not be sent within 15 seconds." | logger -t "nut-notify[$$]"
        fi

elif [ "$NOTIFYTYPE" == "ONBATT" ]
then
        if [ "$SHUTDOWN" != "none" ] && [[ ! "$TIMER" =~ ^[0-9]+$ ]]; then
            SHUTDOWN="sec_timer"; TIMER=30; BATTERY=""
            MESSAGE="The system will shutdown in ${TIMER} seconds (due to malformed shutdown criteria set in GUI)."
            echo "Error: Malformed shutdown criteria, defaulting to ${TIMER} seconds timer..." | logger -t "nut-notify[$$]"
        fi

        echo "[${NAME}] UPS is on battery. ${MESSAGE}" | tee >(wall) >(logger -t "nut-notify[$$]")

        if [ "$(type -t "ONBATT")" == "function" ]; then
            echo "Executing user's hook script for ONBATT (as non-blocking)..." | logger -t "nut-notify[$$]"
            ( ONBATT 2>&1 | logger -t "xnut-notify-hooks.sh[$$]" ) &
        fi

        echo "Sending OS notifications..." | logger -t "nut-notify[$$]"
        timeout -s9 15 "$NOTIFY" -e "${EVENT}" -s "Alert ${SUBJECT} On Battery" -d "UPS is on battery. ${MESSAGE}" -i "alert"
        if [ $? -gt 100 ]; then
            echo "OS notifications could not be sent within 15 seconds." | logger -t "nut-notify[$$]"
        fi

        if [ "$SHUTDOWN" != "none" ]; then
            echo "Shutdown criteria are now being monitored..." | logger -t "nut-notify[$$]"

            if [ "$SHUTDOWN" == "sec_timer" ]; then
                (( n = TIMER ))
                # Loop with one second interval to allow SIGTERM reception.
                while [ $n -ne 0 ]
                do
                        sleep 1
                        (( n-- ))
                done
            else
                timer=$(/usr/bin/upsc "$NAME"@"$IPADDR" "$BATTERY" 2>/dev/null)
                # Loop with one second interval to allow SIGTERM reception.
                # Continue looping if `upsc` output is null or non-numeric until not or `upsmon` sets FSD (LB).
                while [ -z "$timer" ] || [[ ! "$timer" =~ ^[0-9]+([.][0-9]+)?$ ]] || [ "$(printf "%.0f" "$timer")" -gt "$TIMER" ]
                do
                    sleep 1
                    timer=$(/usr/bin/upsc "$NAME"@"$IPADDR" "$BATTERY" 2>/dev/null)
                done
            fi

            echo "Shutdown criteria are now met, proceeding with shutdown..." | logger -t "nut-notify[$$]"
            echo "[${NAME}] UNRAID is being gracefully shutdown from a UPS power event." | tee >(wall) >(logger -t "nut-notify[$$]")

            if [ "$(type -t "ONBATT_SHUTDOWN")" == "function" ]; then
                echo "Executing user's hook script for ONBATT_SHUTDOWN (as non-blocking)..." | logger -t "nut-notify[$$]"
                ( ONBATT_SHUTDOWN 2>&1 | logger -t "xnut-notify-hooks.sh[$$]" ) &
            fi

            echo "Sending OS notifications..." | logger -t "nut-notify[$$]"
            timeout -s9 15 "$NOTIFY" -e "${EVENT}" -s "Alert ${SUBJECT} System Shutdown" -d "UNRAID is being gracefully shutdown from a UPS power event." -i "alert"
            if [ $? -gt 100 ]; then
                echo "OS notifications could not be sent within 15 seconds." | logger -t "nut-notify[$$]"
            fi

            echo "Setting FSD (= point of no return)..." | logger -t "nut-notify[$$]"
            /usr/sbin/upsmon -c fsd
        fi

elif [ "$NOTIFYTYPE" == "REPLBATT" ]
then
        if [ "$REPLBATTMSG" == "enable" ]; then
            echo "[${NAME}] UPS reports that its batteries need replacement." | tee >(wall) >(logger -t "nut-notify[$$]")

            if [ "$(type -t "REPLBATT")" == "function" ]; then
                echo "Executing user's hook script for REPLBATT (as non-blocking)..." | logger -t "nut-notify[$$]"
                ( REPLBATT 2>&1 | logger -t "xnut-notify-hooks.sh[$$]" ) &
            fi

            echo "Sending OS notifications..." | logger -t "nut-notify[$$]"
            timeout -s9 15 "$NOTIFY" -e "${EVENT}" -s "Alert ${SUBJECT} Battery Replacement" -d "UPS reports that its batteries need replacement." -i "alert"
            if [ $? -gt 100 ]; then
                echo "OS notifications could not be sent within 15 seconds." | logger -t "nut-notify[$$]"
            fi
        fi

# for any other status messages the user has configured to be reported
else
        echo "[${NAME}] ${1}" | tee >(wall) >(logger -t "nut-notify[$$]")

        if [ "$(type -t "$NOTIFYTYPE")" == "function" ]; then
            echo "Executing user's hook script for $NOTIFYTYPE (as non-blocking)..." | logger -t "nut-notify[$$]"
            ( "$NOTIFYTYPE" 2>&1 | logger -t "xnut-notify-hooks.sh[$$]" ) &
        fi

        echo "Sending OS notifications..." | logger -t "nut-notify[$$]"
        timeout -s9 15 "$NOTIFY" -e "${EVENT}" -s "Alert ${SUBJECT} Event ${NOTIFYTYPE}" -d "$1" -i "alert"
        if [ $? -gt 100 ]; then
            echo "OS notifications could not be sent within 15 seconds." | logger -t "nut-notify[$$]"
        fi
fi

exit 0
