#!/bin/bash
#
# Copyright Derek Macias
# Copyright macester
# Copyright gfjardim
# Copyright SimonF
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

DOCROOT="/usr/local/emhttp/plugins/nut"

echo "Starting NUT services..."
/etc/rc.d/rc.nut start | logger

[ "${PIPESTATUS[0]}" != 0 ] && touch $DOCROOT/start-failed
