#!/bin/bash
#
# Copyright Derek Macias
# Copyright macester
# Copyright gfjardim
# Copyright SimonF
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

echo "############ USB DEVICES ############"
echo ""
lsusb
echo ""

echo "############ USB DEVICES (TREE VIEW) ############"
echo ""
lsusb -tv
echo ""

echo "############ USB POWER MANAGEMENT SETTINGS ############"
echo ""
tail -v /sys/bus/usb/devices/*/power/control 
echo ""
