#!/bin/bash
#
# Copyright Derek Macias
# Copyright macester
# Copyright gfjardim
# Copyright SimonF
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

CONFIG="/boot/config/plugins/nut/nut.cfg"
[ -e "$CONFIG" ] && source $CONFIG 2>&1

echo "###"
echo "### USB DEVICES"
echo "###"
echo ""
lsusb
echo ""

echo "###"
echo "### USB DEVICES (TREE VIEW)"
echo "###"
echo ""
lsusb -tv
echo ""

echo "###"
echo "### USB POWER MANAGEMENT SETTINGS"
echo "### ON: ALWAYS ON / AUTO: SYSTEM MANAGED"
[ "$ORUSBPOWER" == "enable" ] && echo "###" && echo "### USB POWER MANAGEMENT OVERRIDE ACTIVATED"
echo "###"
echo ""
tail -v /sys/bus/usb/devices/*/power/control 
echo ""

echo "###"
echo "### USB RELATED KERNEL MESSAGES"
echo "###"
echo ""
dmesg | grep "usb"
