#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

if [ -f /etc/logrotate.d/nut ]; then
    echo "Forcing log rotation (reset) on NUT Service Logs..."
    if logrotate -f /etc/logrotate.d/nut; then
        echo "*** LOGS ARE NOW RESET, YOU MAY CLOSE THIS WINDOW ***"
    else
        echo "*** FAILED RESETTING LOGS, PLEASE TRY AGAIN LATER ***"
    fi
else
    echo "Forcing log deletion on inactive NUT Service Logs..."
    if rm -f /var/log/nut.log; then
        echo "*** LOGS ARE NOW DELETED, YOU MAY CLOSE THIS WINDOW ***"
    else
        echo "*** FAILED DELETING LOGS, PLEASE TRY AGAIN LATER ***"
    fi
fi
